package org.dcm4che.ris.api.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.*;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Requested Procedure entity.
 * Represents a specific imaging procedure within an Imaging Service Request.
 * Based on DICOM Requested Procedure Module and IHE Scheduled Workflow Profile.
 *
 * @author dcm4che-ris
 */
@Entity
@Table(name = "requested_procedure", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"accession_number"}),
    @UniqueConstraint(columnNames = {"study_instance_uid"})
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RequestedProcedure implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "requested_procedure_id")
    private Long requestedProcedureId;

    /**
     * Parent Imaging Service Request (Order)
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false)
    private ImagingServiceRequest order;

    /**
     * Requested Procedure ID (0040,1001)
     * Code identifying the procedure
     */
    @Size(max = 64)
    @Column(name = "requested_procedure_id_code", length = 64)
    private String requestedProcedureIdCode;

    /**
     * Requested Procedure Description (0032,1060)
     * HL7: OBR-4
     */
    @Size(max = 255)
    @Column(name = "requested_procedure_description", length = 255)
    private String requestedProcedureDescription;

    /**
     * Study Instance UID (0020,000D)
     * Generated by RIS for this study
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = "study_instance_uid", nullable = false, unique = true, length = 128)
    private String studyInstanceUID;

    /**
     * Accession Number (0008,0050)
     * Unique identifier for this procedure
     * HL7: OBR-18
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = "accession_number", nullable = false, unique = true, length = 64)
    private String accessionNumber;

    /**
     * Reference to Procedure Catalog entry
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "procedure_code_id")
    private ProcedureCatalog procedureCode;

    /**
     * Procedure Priority
     * Values: ROUTINE, URGENT, STAT
     * HL7: OBR-5
     */
    @Size(max = 16)
    @Column(name = "procedure_priority", length = 16)
    @Builder.Default
    private String procedurePriority = "ROUTINE";

    /**
     * Requested Date/Time
     * HL7: OBR-6
     */
    @Column(name = "requested_date_time")
    private LocalDateTime requestedDateTime;

    /**
     * Contrast Agent (0018,0010)
     */
    @Size(max = 64)
    @Column(name = "requested_contrast_agent", length = 64)
    private String requestedContrastAgent;

    /**
     * Patient has contrast allergies
     */
    @Column(name = "contrast_allergies")
    @Builder.Default
    private Boolean contrastAllergies = false;

    /**
     * Pre-medication instructions
     */
    @Column(name = "pre_medication", columnDefinition = "TEXT")
    private String preMedication;

    /**
     * Patient preparation instructions
     */
    @Column(name = "patient_preparation", columnDefinition = "TEXT")
    private String patientPreparation;

    /**
     * Special instructions for this procedure
     */
    @Column(name = "special_instructions", columnDefinition = "TEXT")
    private String specialInstructions;

    /**
     * Reason for the requested procedure
     * HL7: OBR-31
     */
    @Column(name = "reason_for_procedure", columnDefinition = "TEXT")
    private String reasonForProcedure;

    /**
     * Comments on the requested procedure
     */
    @Column(name = "comments", columnDefinition = "TEXT")
    private String comments;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // Relationships

    /**
     * Scheduled Procedure Steps for this requested procedure
     */
    @OneToMany(mappedBy = "requestedProcedure", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<ScheduledProcedureStep> scheduledProcedureSteps = new ArrayList<>();

    /**
     * The DICOM study associated with this procedure
     */
    @OneToOne(mappedBy = "requestedProcedure", cascade = CascadeType.ALL)
    private Study study;

    /**
     * Reports for this procedure
     */
    @OneToMany(mappedBy = "requestedProcedure", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<Report> reports = new ArrayList<>();

    // JPA Callbacks

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
        if (procedurePriority == null) {
            procedurePriority = "ROUTINE";
        }
        if (contrastAllergies == null) {
            contrastAllergies = false;
        }
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    // Business Methods

    /**
     * Add a Scheduled Procedure Step
     */
    public void addScheduledProcedureStep(ScheduledProcedureStep sps) {
        scheduledProcedureSteps.add(sps);
        sps.setRequestedProcedure(this);
    }

    /**
     * Remove a Scheduled Procedure Step
     */
    public void removeScheduledProcedureStep(ScheduledProcedureStep sps) {
        scheduledProcedureSteps.remove(sps);
        sps.setRequestedProcedure(null);
    }

    /**
     * Add a Report
     */
    public void addReport(Report report) {
        reports.add(report);
        report.setRequestedProcedure(this);
    }

    /**
     * Get the patient from the parent order
     */
    public Patient getPatient() {
        return order != null ? order.getPatient() : null;
    }

    /**
     * Check if procedure is urgent
     */
    public boolean isUrgent() {
        return "URGENT".equalsIgnoreCase(procedurePriority) ||
               "STAT".equalsIgnoreCase(procedurePriority);
    }

    /**
     * Check if all scheduled procedure steps are completed
     */
    public boolean areAllSPSCompleted() {
        return scheduledProcedureSteps.stream()
            .allMatch(sps -> sps.getSpsStatus() != null &&
                           sps.getSpsStatus().isTerminal());
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RequestedProcedure)) return false;
        RequestedProcedure that = (RequestedProcedure) o;
        return requestedProcedureId != null &&
               requestedProcedureId.equals(that.requestedProcedureId);
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }

    @Override
    public String toString() {
        return "RequestedProcedure{" +
                "requestedProcedureId=" + requestedProcedureId +
                ", accessionNumber='" + accessionNumber + '\'' +
                ", studyInstanceUID='" + studyInstanceUID + '\'' +
                ", requestedProcedureDescription='" + requestedProcedureDescription + '\'' +
                '}';
    }
}
